name: colorwardrobe
description: "오프라인 색 조합 추천 · 3/5/7일 계획 · 통계 (Flutter)"
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # 상태관리
  flutter_riverpod: ^2.5.1

  # 로컬 저장
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2

  # 이미지/카메라(갤러리 포함)
  image_picker: ^1.1.1

  # 간단 팔레트 추출(옵션)
  palette_generator: ^0.3.3+3

  # 유틸
  collection: ^1.18.0
  intl: ^0.19.0
  table_calendar: ^3.1.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner: ^2.4.9
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/standard_colors.json
